version: '3.5'

services:
  app:
    container_name: media-service
    build:
      context: .
      args:
        DATA_PATH: /data
        BUILD_PATH: /build
      dockerfile: devops/build/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: media-service-postgresql
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: